### ISSUE TITLE
Issue with redcap version and EM pages

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#221] opened 2019-11-12 23:20 UTC
I'm trying to understand what's going on here but it is clear we have an issue with how External Module pages are initialized with REDCap.

Module pages contain the version in the url, e.g.:

```
http://redcap.local/redcap_v9.3.5/ExternalModules/?prefix=my_module&page=myPage&pid=89&NOAUTH...
```

When hit at /redcap_v9.3.5/ExternalModules/index.php:

1. the index.php page requires /classes/ExternalModules.php
1. the ExternalModules.php calls `ExternalModules::callRedcapConnect()`
1. this walks back to the root and includes redcap_connect.php
1. `redcap_connect.php` then gets the current database version (call it 9.3.9) and stores it in `$redcap_version`
1. It then includes `/redcap_v` + `$redcap_version` + `/Config/` + `init_project.php | init_global.php`
1. Which in turn loads the `System` class from the `$redcap_version` folder and calls `System::initProjectPage` or `System::initGlobalPage`.. 
1. These functions then call `checkREDCapVersionRedirect()`.  From here, the global `$redcap_version` is defined - in my example it is "9.3.9".   This is where it gets interesting.

The `checkREDCapVersionRedirect` checks the database version against a variable called `$redcapdir_version` which is determined from:
```
// Set informal docroot
$app_path_docroot = dirname(dirname(__FILE__)).DS;
// Get version we're currently in from the URL
$redcapdir_version = substr(basename($app_path_docroot), 8);
```

This, I think, is the problem.  We started with a 9.3.5 URL and yet because REDCap connect called the `redcap_v9.3.8/Config/init_xxx` BOTH of these return values are the database version (9.3.8 in my example).  So, no redirect is done.

after `checkREDCapVersionRedirect()` returns, the `System::init_xxx` in the `$redcap_version` keeps going...  At the end of this method is `self::initExternalModules`.

This then finds the ExternalModule location and tries to include EM Class Path
```
include_once APP_PATH_EXTMOD . $ExtModClassPath;
```
This throws an error for redeclaring a class that already exists in the same namespace from the previous version of REDCap way back up at step 1:
```
Fatal error: Cannot declare class ExternalModules\ExternalModules, because the name is already in use in /var/www/html/redcap_v9.3.8/ExternalModules/classes/ExternalModules.php on line 29
```

I still have some questions... locally, I seem to get a different outcome than on my shibboleth test server...  Not sure why.  Guessing it has something to do with authentication but haven't gotten there.  I do recall some authentication discussion about EMs and initilization from a long time ago.

What's the solution?  Most redcap pages include `/Config/init_...` right away which handles the redirection since the version from `__FILE__` is still in the URL's version.

One approach is to store the 'original file' in a global context, so when the ExternalModule/index.php is called, we know where we are starting from.  Another would be to use something other than __FILE__ in the `checkREDCapVersionRedirect`.

Thoughts in response to me wasting an afternoon :-)
-A . @taylorr4

**Comment by 123andy** [comment] 2019-11-13 00:21
I'm still confused.  It appears on my 'dev' and prod servers we are throwing an error for trying to instantiate a second instance of ExternalModules.
However, on my local instance, I can't get this to happen.  Could it be different php version settings?  Can you 'return' from an included file before a class is defined and never create that class?  I wouldn't think so...

**Comment by mmcev106** [comment] 2019-11-13 15:35
I am not able to reproduce this on my local.  We can't test this on our test & prod servers since they use the dev location for the EM framework (outside the REDCap version dirs).  I feel like the best solution would fix the redirection issue since allowing an old version of any class to load could cause problems, but I'm not what that fix would look like at the moment.

Adding to the complication, there's already a return at the top of the `ExternalModules` class:
https://github.com/vanderbilt/redcap-external-modules/blob/testing/classes/ExternalModules.php#L21-L23

I remember this being added a couple of years ago when only one of our developers was seeing a class loading issue that we had trouble tracking down.  I wish we had tracked it down instead...

**Comment by taylorr4** [comment] 2019-11-13 16:59
If i go to the Email Alerts module setup page in a project on my dev instance, for example, and then modify the version in the URL to a previous version, it redirects correctly to the current REDCap version.

**Comment by 123andy** [comment] 2019-11-13 21:49
Here is the error I’m getting.  And it is regardless of the module – here is one with Shazam..  This is on php 7.0

https://redcap.stanford.edu/redcap_v9.3.5/ExternalModules/?prefix=shazam&page=config&pid=7945&__display_errors

Fatal error: Cannot declare class ExternalModules\ExternalModules, because the name is already in use in /var/www/html/redcap_v9.3.8/ExternalModules/classes/ExternalModules.php on line 29
REDCap crashed due to an unexpected fatal error!


Locally, it works – but I was on 7.3.  I just switched back down to 7.0 and still can’t reproduce.  I guess I can try copying over the production code and see if I can get that to break locally…
I’m not sure what it is…

**Comment by mmcev106** [comment] 2020-01-21 19:51
I think commit 86a0cb8 might have fixed this issue.  I'm going to go ahead and close this, but please feel free to reopen it if there are more scenarios to consider.

**Closed by mmcev106** 2020-01-21 19:51 UTC
