### ISSUE TITLE
API endpoint url and pid...

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#65] opened 2017-11-16 23:48 UTC
We are a shibboleth shop - which means the only way to pass a url through to external mods without forcing redcap auth is to use the API endpoint (which is exempted).  This is just fine.

However - the api endpoint url does not include the &pid in the query string.  As em pages have a $module object that is an instance of the EM class - the object is different depending on the source url.   In most cases, it comes in project-context (except when you are adding the module to your server).  

In the case of the API - we can get the PID from the external module id which is in the url.  Is there a reason to not do this and populate the $_GET['pid'] so we can attach on a project-level?

Current index code is:
```php
<?php
namespace ExternalModules;

$noAuth = isset($_GET['NOAUTH']);
if($noAuth){
	// This must be defined at the top before redcap_connect.php is required.
	define('NOAUTH', true);
}

require_once dirname(__FILE__) . '/classes/ExternalModules.php';

use Exception;

$id = $_GET['id'];
$page = rawurldecode(urldecode($_GET['page']));
$pid = @$_GET['pid'];

```
I'm proposing something like this:

```php
<?php
namespace ExternalModules;

$noAuth = isset($_GET['NOAUTH']);
if($noAuth){
	// This must be defined at the top before redcap_connect.php is required.
	define('NOAUTH', true);
}

require_once dirname(__FILE__) . '/classes/ExternalModules.php';

use Exception;

$id = $_GET['id'];
$page = rawurldecode(urldecode($_GET['page']));
/*
// IF IS API URL, AND PID IS NOT SET, THE TRY TO GET THE PID FROM THE ID
// IF SUCCESSFUL, SET $_GET['pid'].  This way the module will behave in project-context.
select project_id
            from redcap_external_module_settings
            where external_module_id = $id
            and key='enabled'
            and `value`='true';
...
*/
$pid = @$_GET['pid'];
```
Thoughts?

I just had to do a work-around for one EM and can't think of a reason it should happen automatically...

**Comment by taylorr4** [comment] 2017-11-17 11:43
@123andy, i'm not sure that will work all the time. The only time your proposed query will work is if the module is enabled in **only one project** in the system. If more than one project has it enabled, then it will return all those project_ids in that query to `redcap_external_module_settings`.

I think getUrl works correctly as it is, unless i'm missing something in your argument, in which if you call getUrl in a project context, then it **does** append "pid" to the API endpoint. And if you're not in a project context wen calling getUrl, then i'm not sure how or why you would want it to point to a specific project, unless that project ID is saved in the module's configuration. Maybe i'm missing something here.

**Comment by taylorr4** [comment] 2017-11-17 16:28
I'm not sure of what the behavior should be in those cases. @mmcev106 or @scottjpearson might know.

**Comment by mmcev106** [comment] 2017-11-21 17:46
It is expected behavior for request to php pages to work if php extension is omitted.  It is not currently a priority for us, but I do like the idea of getUrl() throwing an exception for pages/files that don't exist.

**Comment by mmcev106** [comment] 2020-01-21 21:11
Closing for lack of update, and since the current behavior might be the most appropriate.  Feel free to reopen.

**Closed by mmcev106** 2020-01-21 21:11 UTC
Labels: Enhancement
