### ISSUE TITLE
Saving system settings not working for modules enabled in projects

### ISSUE THREAD

**Issue by lsgs** [vanderbilt/redcap-external-modules#311] opened 2020-04-20 11:30 UTC
I've recently upgraded from 9.2.5 to 9.7.8 and I not get the exception below when saving system settings (e.g. to enable user activation permission) for any module that is enabled on one or more projects individually.

save-settings.php passes `null` as the project id to `ExternalModules::saveSettings()`, but in the way the query is built in `ExternalModules::getSettingsQuery()` it seems that this is unexpected - it looks like that method expects a value of `self::SYSTEM_SETTING_PROJECT_ID` rather than null, but that this is in the process of being deprecated.
```
An error occurred while saving settings:

<br />
<b>Fatal error</b>:  Uncaught Exception: More than one (32) External Module setting exists for prefix 'dag_switcher', project ID '', and key 'enabled'! This should never happen! in /site/redcap/redcap_v9.7.8/ExternalModules/classes/ExternalModules.php:2173
Stack trace:
#0 /site/redcap/redcap_v9.7.8/ExternalModules/classes/ExternalModules.php(1846): ExternalModules\ExternalModules::getSetting('dag_switcher', NULL, 'enabled')
#1 /site/redcap/redcap_v9.7.8/ExternalModules/classes/ExternalModules.php(301): ExternalModules\ExternalModules::setSetting('dag_switcher', NULL, 'enabled', false)
#2 /site/redcap/redcap_v9.7.8/ExternalModules/manager/ajax/save-settings.php(22): ExternalModules\ExternalModules::saveSettings('dag_switcher', NULL, Array)
#3 {main}
  thrown in <b>/site/redcap/redcap_v9.7.8/ExternalModules/classes/ExternalModules.php</b> on line <b>2173</b><br />
				<div class="red" style="margin:20px 0px;max-width:700px;">
					<b>REDCap crashed due to an unexpected PHP fatal error!</b><br><br>
					<b>Error message:</b> Uncaught Exception: More than one (32) External Module setting exists for prefix 'dag_switcher', project ID '', and key 'enabled'! This should never happen! in /site/redcap/redcap_v9.7.8/ExternalModules/classes/ExternalModules.php:2173
Stack trace:
#0 /site/redcap/redcap_v9.7.8/ExternalModules/classes/ExternalModules.php(1846): ExternalModules\ExternalModules::getSetting('dag_switcher', NULL, 'enabled')
#1 /site/redcap/redcap_v9.7.8/ExternalModules/classes/ExternalModules.php(301): ExternalModules\ExternalModules::setSetting('dag_switcher', NULL, 'enabled', false)
#2 /site/redcap/redcap_v9.7.8/ExternalModules/manager/ajax/save-settings.php(22): ExternalModules\ExternalModules::saveSettings('dag_switcher', NULL, Array)
#3 {main}
  thrown<br>
					<b>File:</b> /site/redcap/redcap_v9.7.8/ExternalModules/classes/ExternalModules.php<br>
					<b>Line:</b> 2173<br>
				</div>
```

**Comment by mmcev106** [comment] 2020-04-20 15:07
@lsgs, thanks very much for reporting this.  I'd like to prioritize it, but I'm having trouble reproducing the issue on 9.7.8 or the latest version of the testing branch.  Does it only occur with a certain config.json, or after a certain series of events?

**Comment by mmcev106** [comment] 2020-04-20 15:09
If you already have a specific solution in mind, feel free to just send a PR.  I don't necessarily have to reproduce it.

**Comment by grezniczek** [comment] 2020-04-20 16:45
@lsgs , I have seen similar when using a specific version of MariaDB, 10.4 ...
See these community posts:
https://community.projectredcap.org/questions/70157/warning-be-cautious-when-upgrading-to-mariadb-104-1.html
https://community.projectredcap.org/questions/72984/em-framework-and-mariadb-1046-dont-play-nice-due-t.html

Could this be the issue? If you are running 10.4 then likely it is. 
If it is ... this drove me nuts some time ago. The solution in the post works. You'll bave to delete the duplicate entries in the settings table manually, though.

**Comment by lsgs** [comment] 2020-04-20 20:32
Thanks for replying @mmcev106, @grezniczek. 

I'm not sure the problem is quite the same as you found @grezniczek. We're using MariaDb 5.5.64. The query in `ExternalModules::getSettings()` is returning the expected results, it just does not appear to be being built correctly in the method. The `$pid` parameter passed to it is `null` and is therefore ignored in `ExternalModules::getSettingsQuery()` (see ExternalModules.php line 2016, v9.7.8). That means that the query does not include the `and project_id is null` component in the WHERE clause, and hence a row is returned for each project the module is enabled for as well as the (expected) system-level, project_id null row. The `getSettings()` method then throws an exception because it expects only a single row to be returned.

I had a go at adding handling for a null value but it's not PR-ready. I am seeing some other weirdness where a module enabled in a project by a user would just disappear from the project module list and have not yet tracked down what's going on there.

**Comment by grezniczek** [comment] 2020-04-20 21:07
Hmm, @lsgs - I just had a look at the code. save-settings.php should not pass `null` for pid in case of system settings, but an empty string `""`. Also, this never gets processed by getSettingsQuery (which expects its parameters in array form).

So if you actually do see `null` being passed from within save-settings.php, then something is going wrong _before_.

**Comment by lsgs** [comment] 2020-04-21 05:24
Hello @grezniczek. save-settings.php sets `$pid` at line 5 like this:
```
$pid = @$_GET['pid'];
```
so it's `null` for system settings. It's unchanged - still `null` - at line 22 when it gets passed to `ExternalModules::saveSettings()`:
```
$saveSqlByField = ExternalModules::saveSettings($moduleDirectoryPrefix, $pid, $rawSettings);
```
It gets to the call to `getSettingsQuery()` via `setSetting()` and within that a call to `getSetting()` (to get the existing value).

**Comment by grezniczek** [comment] 2020-04-21 05:48
Hi @lsgs ,
I guess you are calling save-settings.php yourself, i.e. not through the framework's GUI?

The framework ever calls this ajax method like so:
`.../manager/ajax/save-settings.php?pid=&moduleDirectoryPrefix=redcap_em_config_study`

Note the `pid=` in the parameters. This results in `$pid = ""` in line 5.

While `save-settings.php` is "private" to the framework and not meant to be called _from outside_, it still might be a good idea to check after line 5 and add:
```php
if ($pid === null) { $pid = ""; }
```

**Comment by lsgs** [comment] 2020-04-21 20:34
Hello @grezniczek. I'm just clicking "Save" in the Control Centre module configuration dialog. You're right that the POST includes `pid=` in the query string:
https://localhost/redcap_v9.7.8/ExternalModules/manager/ajax/save-settings.php?pid=&moduleDirectoryPrefix=auto_dags

Interestingly, however, I find that `$pid = @$_GET['pid'];` gives me (locally and on server) `null` for `$pid`, not an empty string. What makes that difference I wonder? 

Your suggested fix works well though. I find things function as expected with that inserted at line 6 of save-settings.php.
```
if ($pid === null) { $pid = ""; }
```

**Comment by lsgs** [comment] 2020-04-21 21:21
[PR](https://github.com/vanderbilt/redcap-external-modules/pull/314) submitted

**Comment by grezniczek** [comment] 2020-04-21 21:35
Hmm, that's interesting. I guess you checked in browser dev tools. Can you verify that the query string arrives at PHP intact? 
Use `$url = $_SERVER['REQUEST_URI'];` in line 3.

What PHP version are you running?

**Comment by grezniczek** [comment] 2020-04-21 21:49
Just found this: https://www.php.net/manual/en/reserved.variables.get.php
Check out the first comment.

**Comment by 123andy** [comment] 2020-04-22 00:44
since 0 isn't a valid value, I usually use empty() to avoid all of the php typing challenges... probably not a great practice but I think I avoid more little issues like this than I create.

**Comment by mmcev106** [comment] 2020-04-23 21:24
The PR has been merged.  Thanks very all, especially @lsgs.

**Closed by mmcev106** 2020-04-23 21:24 UTC
